PATH_TO_ALL_IMAGES: "../images/all_images"
PATH_TO_LABEL_MAP: "../TensorFlow/workspace/project_museum/annotations/label_map.pbtxt"
PATH_TO_PRETRAINED_MODEL: "../TensorFlow/workspace/project_museum/pre-trained-models/centernet_hg_104_512x512_coco17_tpu-8/saved_model"
PATH_TO_EXPORTED_MODEL: "../TensorFlow/workspace/project_museum/exported-models/centernet_hg_104_512x512_coco17_tpu-8/saved_model"
PATH_TO_PLOTS: "../images/plots/"
PATH_TO_ML_BACKEND_MODEL: "../../Tensorflow/workspace/project_museum/pre-trained-models/centernet_hg_104_512x512_coco17_tpu-8"