PATH_TO_ALL_IMAGES: "./images/all_images"
PATH_TO_DETECTED_PERSON: "./images/detected_persons"
PATH_TO_NOT_RELEVANT_LABEL: "./images/not_relevant_label"
PATH_TO_LABEL_MAP: "./TensorFlow/workspace/model1/annotations/label_map.pbtxt"
PATH_TO_MODEL: "./TensorFlow/workspace/model2/pre-trained-models/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8/saved_model"
PATH_TO_EXPORTED_MODEL: "./TensorFlow/workspace/model1/exported-models/myModel/saved_model"
PATH_TO_PLOTS: "./images/plots/"